name: CodeNotary

on: [push]

jobs:
  check:

    runs-on: windows-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@master
     
     - name: Verify
       uses: vchain-us/verify-action@master
